#ifndef _TSG_H
#define _TSG_H

#define CLOCK_PERIOD    10              /* clock period in microseconds */

#define TSG_OK 0
#define TSG_INV_RSEP 1
#define TSG_NO_SMSEP 2
#define TSG_INV_MPPUL_SMSEP 3
#define TSG_INV_PAT 4
#define TSG_INV_MPINC_SMSEP 5
#define TSG_INV_LAGFR_SMSEP 6
#define TSG_INV_DUTY_CYCLE 7
#define TSG_INV_ODD_SMSEP 8
#define TSG_INV_TXPL_BAUD 9
#define TSG_INV_MEMORY 10
#define TSG_INV_PHASE_DELAY 11


struct TSGbuf {
  int32_t index;
  int32_t len;
  int32_t step;  //packed timesequence stepsize in microseconds
  unsigned char *code;
  unsigned char *rep;
};

struct TSGprm {
  int32_t nrang,          /* number of ranges */
      frang,          /* distance to first range */
      rsep,           /* range gate separation */
      smsep,          /* sample separation */
      lagfr,
      txpl,           /* length of pulse */
      mppul,          /* number of pulses in the sequence */
      mpinc,          /* multi-pulse increment */
      mlag,           /* maximum lag in the sequence */
      nbaud,          /* number of baud in the phase code */
      samples,        /* number of samples generated by the sequence */
      smdelay,        /* sample delay */
      stdelay,        /* delay at front of sequence */
      gort;           /* gate or trigger with scope sync*/
  int32_t rtoxmin;        /* delay between receiver off and pulse */
  int32_t *pat,       /* pointer to the pulse pattern */
          *code;      /* pointer to the phase code table */
};


void TSGFree(struct TSGbuf *ptr);
#endif
