#!/bin/sh
cd $HOME
$HOME/src/cp_files dat dat
$HOME/src/cp_files fit fit
$HOME/src/cp_files fit inx
$HOME/src/cp_files rawacf rawacf
$HOME/src/cp_files fitacf fitacf
$HOME/src/cp_files snd snd
$HOME/src/ftp_seqlog 
#
#$HOME/src/cdproc

