# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_msg', [dirname(__file__)])
        except ImportError:
            import _msg
            return _msg
        if fp is not None:
            try:
                _mod = imp.load_module('_msg', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _msg = swig_import_helper()
    del swig_import_helper
else:
    import _msg
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


UNKNOWN_HOST = _msg.UNKNOWN_HOST
OPEN_FAIL = _msg.OPEN_FAIL
CONNECT_FAIL = _msg.CONNECT_FAIL
MSG_ID = _msg.MSG_ID
MSGERR_PIPE_CLOSED = _msg.MSGERR_PIPE_CLOSED
MSGERR_OUT_OF_SYNC = _msg.MSGERR_OUT_OF_SYNC
MSGERR_NOMEM = _msg.MSGERR_NOMEM

def ConnexWriteMem(*args):
  return _msg.ConnexWriteMem(*args)
ConnexWriteMem = _msg.ConnexWriteMem

def ConnexReadMem(*args):
  return _msg.ConnexReadMem(*args)
ConnexReadMem = _msg.ConnexReadMem

def ConnexWriteIP(*args):
  return _msg.ConnexWriteIP(*args)
ConnexWriteIP = _msg.ConnexWriteIP

def ConnexReadIP(*args):
  return _msg.ConnexReadIP(*args)
ConnexReadIP = _msg.ConnexReadIP

def print_args(*args):
  return _msg.print_args(*args)
print_args = _msg.print_args
# This file is compatible with both classic and new-style classes.

cvar = _msg.cvar

